// Rathor-NEXi Service Worker – Mercy-gated offline support
// Using Workbox v6.5.4 (CDN) – stable & lightweight
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.5.4/workbox-sw.js');

workbox.setConfig({ debug: false }); // Set true only during local dev

// Precache manifest (auto-generated by build or manual list)
workbox.precaching.precacheAndRoute(self.__WB_MANIFEST || []);

// Navigation requests → stale-while-revalidate (fast + fresh)
workbox.routing.registerRoute(
  ({ request }) => request.mode === 'navigate',
  async ({ event }) => {
    try {
      return await workbox.strategies.staleWhileRevalidate({
        cacheName: 'rathor-pages',
        plugins: [
          new workbox.cacheableResponse.CacheableResponsePlugin({ statuses: [0, 200] })
        ]
      }).handle({ event });
    } catch (err) {
      // Mercy offline fallback page
      return caches.match('/offline.html') || new Response(
        '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Offline Mercy Thunder</title><style>body{background:#0a0015;color:#ffdd44;font-family:sans-serif;text-align:center;padding:40px;}h1{color:#ffaa00;}</style></head><body><h1>Offline Mercy Thunder ⚡️</h1><p>Lattice resting. Reconnect to awaken.</p></body></html>',
        { headers: { 'Content-Type': 'text/html' } }
      );
    }
  }
);

// Cache-first for static assets (icons, images, fonts)
workbox.routing.registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|ico|woff2?|ttf)$/,
  new workbox.strategies.CacheFirst({
    cacheName: 'rathor-static',
    plugins: [
      new workbox.expiration.ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days
      })
    ]
  })
);

// Network-first for future dynamic API calls
workbox.routing.registerRoute(
  /\/api\//,
  new workbox.strategies.NetworkFirst({
    cacheName: 'rathor-dynamic',
    networkTimeoutSeconds: 3
  })
);

// Install → skip waiting so new SW activates immediately
self.addEventListener('install', event => {
  self.skipWaiting();
});

// Activate → claim clients so new SW controls pages instantly
self.addEventListener('activate', event => {
  event.waitUntil(self.clients.claim());
});
